### ISSUE TITLE
Top bar organization

### ISSUE THREAD

**Issue by hseliger** [fthx/task-up#1]
Hi!

Nice rewrite of BaBar! Looks great!

One thing still making me keep my patched version of BaBar: the top bar gets mixed up all the time. While BaBar seemed to have kept all icons in one group, that I could put to the right place (I use Top Bar Organizer for that), Task Up now creates a new entry for each window or app it shows. So I guess once every possible window has shown at least once, I could organize them, but the list of windows to keep is then horrendously long and unmaintainable. And every new program ends up on the right end of the left block again.

Would there be a way to put the Task Up icons in a group of some sorts?

Cheers!
Hendrik

**Comment by fthx** [comment]
Maybe it could be possible to create a sort of group.
But at the moment, each window is shown through a PanelMenu.Button (that allows a very simple way to have its app menu).
I'll have a look at this, but for sure it won't be a boxLayout as Babar.

**Comment by fthx** [comment]
Hi,

It's been done but now reverted. If this is is important for you, you can find the drag and drop version here:
https://extensions.gnome.org/review/50248

**Comment by fthx** [comment]
Hi all, Dnd is back soon.
BTW when GNOME extensions website will be online again. ;-)

There is no more issue with this feature (cf. BaBar).

**Comment by fthx** [comment]
For everyone: dnd is ok now in GS website version.
