### ISSUE TITLE
[FEATURE REQUEST] Turn off drag, drop.

### ISSUE THREAD

**Issue by orcbolg3612** [fthx/task-up#2]
drag and drop feature make me sometime can't change tab fast because sometime i click into top border of tab and change tab is invalid. fuck drag and drop.

**Comment by orcbolg3612** [comment]
btw, I also see your extension quite laggy when i am changing tab too much....

**Comment by fthx** [comment]
*Hi*,

That's because I have to check for long press since there is two functions for left button.
I have to see if I remove dnd or make a pref.
I'm not completely satisfied with dnd state.

**Comment by fthx** [comment]
I removed dnd.
The code is uploaded here and soon in GS ext website.

**Comment by orcbolg3612** [comment]
> I removed dnd. The code is uploaded here and soon in GS ext website.

Can you also remove this bug?I dunnowhat else to call it.

https://github.com/fthx/task-up/assets/154581201/71ca2a56-ae87-4a09-8a4d-ca292cab38d6

**Comment by fthx** [comment]
This screencast is not that clear.
Please describe what you did, expect, etc.

**Comment by fthx** [comment]
So I'm on my laptop now, you want the top margin to be removed ?

**Comment by fthx** [comment]
That's not a bug but I can change that in CSS.

**Comment by orcbolg3612** [comment]
> This screencast is not that clear. Please describe what you did, expect, etc.

What I mean is that my mouse pointer turns into a 4 arrow when I click on the top corner of the app tab and then switching tabs by clicking on another tab with the mouse pointer like that is disabled. 

> So I'm on my laptop now, you want the top margin to be removed ?

Sr for my late

**Comment by fthx** [comment]
https://github.com/fthx/task-up/commit/37f24bd53aed79d6b70f894bfd8a04834a4a9864

Reopen this if needed.

**Comment by fthx** [comment]
That's reviewed in GS ext website, you should have the update now.

**Comment by emascandam** [comment]
Hello, I was a user of Babar Lite and recently moved to Gnome 46. I used the drag and drop feature a lot to organize my workspaces. It is faster than double-pressing Super (or Super+D on Pop). It was especially helpful with tiling window managers because sometimes I need more space and this allowed me to move a window quickly from the top bar without turning away from what I am currently doing. Is it possible to add it as a preference instead of completely removing it?
Many thanks for developing this extension as well as Babar Lite.

**Comment by fthx** [comment]
Hi, this feature was made but did not make me happy with.
Having to recognize a drag vs a simple click made the extension not very responsive.

So, if somebody improves the code (that you can find in some of the commits), why not. But that's heavy for just a secondary option.

**Comment by fthx** [comment]
Hi all, Dnd is back soon.
BTW when GNOME extensions website will be online again.  ;-)

There is no more issue with this feature (cf. BaBar).

**Comment by fthx** [comment]
Could you test dnd with current version?
Please use github's version until it's reviewed in GS website. (Ordering issues have been addressed, afaics.)

**Comment by fthx** [comment]
This feature is online as an update now.
