### ISSUE TITLE
Feature Request: add the workspace number before its open windows on the top bar

### ISSUE THREAD

**Issue by emascandam** [fthx/task-up#3]
Hello,
A rather handy feature of Babar Lite was the ability to see [the page number followed by the windows open on it](https://extensions.gnome.org/extension-data/screenshots/screenshot_4681.png). Is it possible to add this feature to Task Up?
Many thanks.

**Comment by fthx** [comment]
Hi,

This one is possible.
The tasks are ordered by:
1) workspace
2) creation time

So it won't be so hard to include a number.
I'll work on this.

**Comment by fthx** [comment]
WIP!
It's working.
I have to style the buttons, add click action and expose a preference. Not a big deal by far.

VS Babar, TaskUp is much cleaner: all the buttons live their own life, the taskbar is not entirely redrawed on any change. Not a speed issue, but the objects are now correctly destroyed. And I get no errors in logs.

**Comment by fthx** [comment]
Would you accept to test the new version?
It's not buggy for GS itself, need some small changes for workspaces button updates ATM.

**Comment by fthx** [comment]
https://github.com/fthx/task-up/commit/3ce359ae2d2716a86b0c2b2e5273baed1d667890

There's a new 'show activities' setting, because of that.

**Comment by infeeeee** [comment]
I use task-up with the option "Show tasks on active workspace only". But when I login to Gnome Shell, this new option overrides that setting, and I can see all icons with from all workspaces with the numbers.

If I change any extension settings back and forth it changes to the correct behavior.

Steps to reproduce:
1. Enable the setting "Show tasks on active workspace only"
2. Tasks from the active workspace are visible only, workspace numbers are hidden
3. Log out and log in
4. Tasks from all workspaces are visible, workspace numbers are visible
5. Go to extension settings change any option back and forth, task up behaves as it should

**Comment by infeeeee** [comment]
I found another bug related to this. If I create a new workspace, it's number added to the end.

![kép](https://github.com/user-attachments/assets/ecc61969-b38c-4179-8c20-6ec77019119f)

On the screenshot: You can see, this is my first workspace, the icons visible are the apps on that workspace. I just created a new workspace, a fourth. 

Again changing some settings back and forth makes everything working, until I create a new workspace.

**Comment by fthx** [comment]
Yep there are some ordering bugs, I'm refactoring the code since yesterday to solve all this.
Your bug is another one, remind me this if I forget to address it.

**Comment by fthx** [comment]
Ok I found the root ordering issue.
I've got 2 solutions to this. Maybe tomorrow I'll publish the new version.

**Comment by fthx** [comment]
Could you try the new code (uploaded just in this GitHub)?

**Comment by fthx** [comment]
It's now ok too if you use static workspaces.

**Comment by infeeeee** [comment]
I'm on version 40, and with dynamic workspaces if I create a new workspace its number shows up, but not the apps from there:

![kép](https://github.com/user-attachments/assets/f335a017-382a-4ea7-a7b4-a4fb62652b12)

On Workspace 5:

![kép](https://github.com/user-attachments/assets/e9cdf510-6297-4c48-9f85-22d4910ba286)

For this screenshot I reloaded Task-Up with 4 workspaces, and created 2 new workspaces, their numbers are visible. 

Apps on the new workspaces don't show up, as expected, so it affects only the workspace number.

**Comment by fthx** [comment]
Could you please tell me a step-by-step way to reproduce?
I don't understand e.g. your dynamic ws creation with apps.

**Comment by fthx** [comment]
Ok, I got it.
https://github.com/fthx/task-up/commit/cd52b03b81a450ae99008de9df638fd601f92ab6
Tell me if it's ok now.

**Comment by infeeeee** [comment]
Yes!  Version 41 seems like it's working! Thank you!
