### ISSUE TITLE
Visual bug: Non existing app being shown in task up

### ISSUE THREAD

**Issue by TuTiuTe** [fthx/task-up#5]
A mysterious app with the system icon and named @!0,0;BDHF pops up every time I boot my computer
clicking on it does nothing, and hovering reveals its name
it doesn't close when trying to right click and force close it
it also doesn't appear in any process viewer, which makes me think it's an issue with the extension

Like my other issue, "refreshing" the extension makes the problem disappear

![Screenshot from 2024-07-30 13-44-49](https://github.com/user-attachments/assets/8edd8333-aa01-44f4-a6c9-91c0a7e06f0e)

Problem disappearing after refresh
![Screenshot from 2024-07-30 13-45-06](https://github.com/user-attachments/assets/0942b228-24bd-4f64-a53b-605a5bb2edcd)

I am on Fedora 40 and this seems to be an issue since the last version

**Comment by fthx** [comment]
Do you use Desktop Icons extension?

**Comment by fthx** [comment]
Do you have any startup app?

**Comment by TuTiuTe** [comment]
I have no startup apps however I did have the Desktop Icons extensions
I removed it and the phantom app disappeared, I did not use Desktop Icons much so this solves the issue for me

**Comment by fthx** [comment]
Ok I got this issue some time ago with Babar or another extension.
I have to remind me how I filtered Desktop Icons ghost window. But I succeeded to avoid this bug.
So I reopen for others.

**Comment by fthx** [comment]
Ok, Desktop Icons ghost window is type == NORMAL so not filtered for taskbar.
I think it's a bug in DI extension but I look how to workaround this.

**Comment by fthx** [comment]
I reproduced the bug, of course.

**Comment by fthx** [comment]
mmmh, this window should not be created since window.is_skip_taskbar() is true:
https://github.com/fthx/task-up/blob/65b3aae1ee8c9ebd1320ee724d71a62238fdcbf8/extension.js#L446

**Comment by fthx** [comment]
that was the way I did in BaBar to remove Desktop Icons ghost window.

**Comment by fthx** [comment]
Ok, so the Desktop Icons ghost window is not set to skip taskbar at GS startup.
When I check this in LG, the window HAS skip taskbar.

I scratch my head and I'll be back.  ^_^

**Comment by fthx** [comment]
Got it!
https://github.com/fthx/task-up/commit/8387c33b30fad4117f37fbc1bd2d7c5b8dd38303
