### ISSUE TITLE
Feature request: Option to Disable Workspaces Icons

### ISSUE THREAD

**Issue by ghost** [fthx/task-up#6]
Hi,

Could you please add an option to disable workspaces icons? I found the interface ideal without them and would appreciate the ability to turn them off while still being able to view all the apps open across the workspaces.

Thank you!

**Comment by fthx** [comment]
Ok that's by far not a big deal to make this.

**Comment by fthx** [comment]
https://github.com/fthx/task-up/commit/754953f9c127f7e41aa69bb01e77c0bc57ae129a

Feel free to reopen if this is not what you expected.

**Comment by fthx** [comment]
Should be available soon as an update through GS usual process.

**Comment by ghost** [comment]
Thank you! :D
