### ISSUE TITLE
[BUG] Wrong icon on some apps

### ISSUE THREAD

**Issue by TuTiuTe** [fthx/task-up#7]
![image](https://github.com/user-attachments/assets/d92dad3a-2ec9-4a9e-9985-699b5c717737)
Here I have RhythmBox and Evince opened, which both have this default gears in a square icon, which is not theirs

Once I disable and enable the extension again, the issue is solved
![image](https://github.com/user-attachments/assets/d2f9f2a6-5ad2-461f-a7fc-36755ce9ca1d)
However the bug reappears after reboot

I am on Fedora 41, however I discovered this bug before switching from 40, however I don't know if it's a distro related issue
It only seems to be happening with a few system apps such as those two

**Comment by fthx** [comment]
Salut,

Forza les maths.
Je regarde ça dès que possible mais pour le moment je suis au taquet.
Les icônes roue sont obtenues lorsque rien n'a été trouvé.

I'll look at this as soon as possible, around end of November.
Please paste here the result of Logs for "js" keyword.
Please paste your exact version of GNOME Shell too.

++

**Comment by fthx** [comment]
Ok I can reproduce with Evince, Ubuntu 25.04 dev, GS 47.0.

**Comment by fthx** [comment]
I found the (non obvious) trick by reading Window List code...
https://github.com/fthx/task-up/commit/938208e0847ceece43686aa1f7d495c6ba608208

Feel free to reopen if needed.

**Comment by TuTiuTe** [comment]
You were really fast on this one, I did not have time to post the log
It is working now, thx !!

**Comment by fthx** [comment]
During math exam monitoring. ;-)

I had some luck, the change is tiny.
Signals in GNOME Shell are painful, as usual.
