### ISSUE TITLE
Feature request: Show apps button

### ISSUE THREAD

**Issue by peterfilipek** [fthx/task-up#8]
I would like to request additional feature show apps button.
The button should be displayed on the left edge of the taskbar.

Best regards,
Peter

**Comment by fthx** [comment]
Ok I'll do that.
The code is ready from BaBar extension, just have to copy it and make a new prefs setting.

**Comment by fthx** [comment]
It should be updatable soon.

https://github.com/fthx/task-up/commit/36a0d2211dcd97e740c805c95bc6492aec037e39
